// 도메인을 언론사 이름으로 변환하는 매핑
export const domainToPressName: Record<string, string> = {
  'chosun.com': '조선일보',
  'joongang.co.kr': '중앙일보',
  'donga.com': '동아일보',
  'hani.co.kr': '한겨레',
  'khan.co.kr': '경향신문',
  'mk.co.kr': '매일경제',
  'hankookilbo.com': '한국일보',
  'seoul.co.kr': '서울신문',
  'munhwa.com': '문화일보',
  'segye.com': '세계일보',
  'kukinews.com': '국민일보',
  'yna.co.kr': '연합뉴스',
  'news1.kr': '뉴스1',
  'newsis.com': '뉴시스',
  'kbs.co.kr': 'KBS',
  'imbc.com': 'MBC',
  'sbs.co.kr': 'SBS',
  'ytn.co.kr': 'YTN',
  'jtbc.co.kr': 'JTBC',
  'chosunbiz.com': '조선비즈',
  'edaily.co.kr': '이데일리',
  'asiatoday.co.kr': '아시아경제',
  'seouleconews.com': '서울경제',
  'fnnews.com': '파이낸셜뉴스',
  'heraldcorp.com': '헤럴드경제',
  'dt.co.kr': '디지털타임스',
  'etnews.com': '전자신문',
  'ohmynews.com': '오마이뉴스',
  'pressian.com': '프레시안',
  'nocutnews.co.kr': '노컷뉴스',
  'dailian.co.kr': '데일리안',
  'inews24.com': '아이뉴스24',
  'mediatoday.co.kr': '미디어오늘',
  'busan.com': '부산일보',
  'kookje.co.kr': '국제신문',
  'jeonmae.co.kr': '전매일보',
  'kwnews.co.kr': '강원일보',
  'jejuilbo.net': '제주일보',
  'cbs.co.kr': 'CBS',
  'tbs.seoul.kr': 'TBS',
  'tvn.co.kr': 'tvN',
  'channela.co.kr': '채널A',
  'chosuntv.com': 'TV조선',
  'mbn.co.kr': 'MBN',
  'sbsbiz.co.kr': 'SBS Biz',
  'bloter.net': '블로터',
  'zdnet.co.kr': '지디넷코리아',
  'ddaily.co.kr': '디지털데일리',
  'thefact.co.kr': '더팩트',
  'koreatimes.com': '코리아타임스',
  'koreaherald.com': '코리아헤럴드',
  'koreajoongangdaily.com': '코리아중앙데일리',
  'news.naver.com': '네이버 뉴스',
  'n.news.naver.com': '네이버 뉴스',
  'hankyung.com': '한국경제',
  'mt.co.kr': '머니투데이',
  'etoday.co.kr': '이투데이',
  'newstomato.com': '뉴스토마토',
  'sisain.co.kr': '시사IN',
  'womennews.co.kr': '여성신문',
  'betanews.net': '베타뉴스',
  'polinews.co.kr': '폴리뉴스',
  'ajunews.com': '아주경제',
  'newspim.com': '뉴스핌',
  'upkorea.net': '업코리아',
  'newstapa.org': '뉴스타파',
  'consumergyeongje.com': '소비자경제신문',
  'seoulwire.com': '서울와이어',
  'womandonga.com': '여성동아',
  'sisajournal.com': '시사저널',
  'sports.chosun.com': '스포츠조선',
  'sportsseoul.com': '스포츠서울',
  'sports.donga.com': '스포츠동아',
  'isplus.com': '일간스포츠',
  'knnews.co.kr': '경남신문',
  'usnews.co.kr': '울산신문',
  'daejonilbo.com': '대전일보',
  'imsnews.com': '매일신문',
  'mdilbo.com': '무등일보',
  'yeongnam.com': '영남일보',
  'kbin.co.kr': '경북일보',
  'incheonilbo.com': '인천일보',
  'osen.co.kr': 'OSEN',
  'mydaily.co.kr': '마이데일리',
  'xportsnews.com': '엑스포츠뉴스',
  'gbnews.co.kr': '골든브릿지뉴스',
  'ybs.co.kr': 'YBS 연합뉴스방송',
  // 추가 언론사 도메인 매핑 (누락된 것만 추가)
  'yonhapnews.co.kr': '연합뉴스',
  'yonhapnewstv.co.kr': '연합뉴스TV',
  'channel-a.co.kr': '채널A',
  'hdtv.co.kr': '한국경제TV',
  'bizwatch.co.kr': '비즈워치',
  'sedaily.com': '서울경제',
  'moneys.mt.co.kr': '머니S',
  'thescoop.co.kr': '더스쿠프',
  'lady.khan.co.kr': '레이디경향',
  'sisapress.com': '시사저널',
  'san.chosun.com': '월간 산',
  'economist.co.kr': '이코노미스트',
  'weekly.khan.co.kr': '주간경향',
  'weekly.donga.com': '주간동아',
  'weekly.chosun.com': '주간조선',
  'sunday.joongang.co.kr': '중앙SUNDAY',
  'h21.hani.co.kr': '한겨레21',
  'magazine.hankyung.com': '한경비즈니스',
  'journalist.or.kr': '기자협회보',
  'nongmin.com': '농민신문',
  'dongscience.com': '동아사이언스',
  'ildaro.com': '일다',
  'kormedi.com': '코메디닷컴',
  'health.chosun.com': '헬스조선',
  'gangwonilbo.com': '강원도민일보',
  'kgnews.co.kr': '경기일보',
  'mudeung.com': '무등일보',
  'jibs.co.kr': 'JIBS',
  'kbc.co.kr': 'kbc광주방송',
  'cjb.co.kr': 'CJB청주방송',
  'jeonjumbc.co.kr': '전주MBC',
  'daegumbc.co.kr': '대구MBC',
};

// 도메인을 언론사 이름으로 변환하는 함수
export const getPressNameFromDomain = (domain: string): string => {
  return domainToPressName[domain] || domain;
};

